Completes task 6
ollycrossley/be-news pull request #6
Opened 2023-08-15 14:06 UTC by ollycrossley

2023-08-15 15:25 UTC, xViolaine requested changes
Hey there! Added some comments for you to consider, please resubmit :)

2023-08-15 15:25 UTC, xViolaine commented on __tests__/app.test.js
> +            test('GET 200   | Return 200 and array with correct comment objects', () => {
We would still expect a test with a 200 if the article exists, when there are no comments

2023-08-15 15:25 UTC, xViolaine commented on models/articles-models.js
> +    `, [param_id]).then(({rows}) => {
See comment re: testing - if the ID is valid and the article exists but there are no comments for the article, we just want to return an empty array

2023-08-16 07:55 UTC, MRombi approved these changes
Good to merge 🙂

2023-08-16 07:57 UTC, merged